services:
  rust-tauri: 
    container_name: deb-builder

    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - ./:/root/project

    privileged: true    # For flatpak: https://github.com/flatpak/flatpak/issues/1326
    
    # keep the container running forever, so that you can connect into it with VS Code DevContainers
    command: sh -c 'while true; do sleep 3600; done'
